name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  update-packages:
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4

      - name: prepare
        run: brew install ruby

      - name: package
        run: ruby package.rb

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: temp/*.c3l

  release:
    runs-on: ubuntu-latest
    needs: [update-packages]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages
          
      - name: delete previous tag
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest',
              sha: context.sha
            })
            
      - name: create latest tag
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/latest',
              sha: context.sha
            })

      - name: Create release and upload packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: packages/*.c3l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
